baseURL: https://hugo.mccdama.fr
languageCode: en-us
title: McCdama
theme: "PaperMod"
ShowReadingTime: true
ShowShareButtons: true
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: false
disableSpecial1stPost: false
disableScrollToTop: false
comments: false
hidemeta: false
hideSummary: false
showtoc: false
tocopen: false
label:
  text: "Home"
params:
  ShowShareButtons: true

markup:
    highlight:
     # anchorLineNos: true
     codeFences: true
     guessSyntax: true
     lineNos: true
     style: monokai
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: example
      name: example.org
      url: https://example.org
      weight: 30
