baseURL = 'https://hugo.mccdama.fr'

[context.production.environment]
  HUGO_VERSION = "0.83.1"


[context.deploy-preview.environment]
HUGO_VERSION = "0.83.1"


[build]
publish = "public"
command = "hugo --gc --minify"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200